# Generated by Django 4.0.3 on 2022-04-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='router',
            name='Alteon_MAC',
        ),
    ]
