# Generated by Django 4.0.3 on 2022-04-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_router_alteon_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adc',
            name='Router_Management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.router'),
        ),
    ]
