# Generated by Django 4.0.3 on 2022-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_router_management'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adc',
            name='Rack',
        ),
        migrations.AlterField(
            model_name='adc',
            name='Form',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adc',
            name='RAM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adc',
            name='SSL_Card',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adc',
            name='State',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='adc',
            name='Version',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
