# Generated by Django 4.0.3 on 2022-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_remove_adc_rack_alter_adc_form_alter_adc_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adc',
            name='Version',
            field=models.CharField(blank=True, max_length=200, verbose_name='can be blank'),
        ),
    ]
