# Generated by Django 4.0.3 on 2022-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_alter_adc_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adc',
            name='Version',
            field=models.CharField(blank=True, default='can be blank', max_length=200),
        ),
    ]
