# Generated by Django 4.0.4 on 2022-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_adc_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adc',
            name='Platform',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
