# Generated by Django 4.0.4 on 2022-04-18 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADC',
            fields=[
                ('MAC', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Platform', models.CharField(max_length=200)),
                ('Rack', models.IntegerField(default=0)),
                ('RAM', models.CharField(max_length=200)),
                ('SSL_Card', models.CharField(max_length=200)),
                ('Version', models.CharField(max_length=200)),
                ('Owner', models.EmailField(max_length=200)),
                ('Console', models.CharField(max_length=200)),
                ('Management', models.CharField(max_length=200)),
                ('Management_Port', models.CharField(max_length=200)),
                ('Management_Vlan', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('Router_Management', models.CharField(max_length=200)),
                ('Vlans', models.CharField(max_length=200)),
                ('User_name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Form', models.CharField(max_length=200)),
                ('Usage_Days', models.PositiveIntegerField(blank=True, null=True)),
                ('Notes', models.CharField(blank=True, max_length=200, null=True)),
                ('Date_usage', models.DateField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Device_Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('Management', models.GenericIPAddressField()),
                ('User_name', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Alteon_MAC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.adc')),
            ],
        ),
    ]
