# Generated by Django 4.0.4 on 2022-05-08 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_alter_adc_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adc',
            options={'ordering': ['Management']},
        ),
        migrations.AddField(
            model_name='adc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='adc',
            name='MAC',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='adc',
            name='Management',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='adc',
            name='Vlans',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
