# Generated by Django 4.0.4 on 2022-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_adc_options_adc_id_alter_adc_mac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adc',
            name='MAC',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
